exports.el = {
    inputName: 'input[data-qa="signup-name"]',
    inputEmail: 'input[data-qa="signup-email"]',
    signupButton: 'button[data-qa="signup-button"]',
    valueName: '#name',
    valueEmail: '#email',
    title: 'input[value=',
    pass: '#password',
    day: '#days',
    month: '#months',
    year: '#years',
    newsletter: '#newsletter',
    optin: '#optin',
    firstName: '#first_name',
    lastName: '#last_name',
    company: '#company',
    address1: '#address1',
    address2: '#address2',
    country: '#country',
    state: '#state',
    city: '#city',
    zipCode: '#zipcode',
    number: '#mobile_number',
    submitButton: 'button[data-qa="create-account"]',
    sucessfuMessage: 'h2[data-qa="account-created"]',
    errorMessage: '#form form[method="POST"] p',
    loginEmail: 'input[data-qa="login-email"]',
    loginPass: 'input[data-qa="login-password"]',
    submitLogin: 'button[data-qa="login-button"]',
    loginForm: '#form'

}